use_frameworks!

target 'ArbitraryJSONCodable_Example' do
  pod 'ArbitraryJSONCodable', :path => '../'

  target 'ArbitraryJSONCodable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
