whitelist_rules:
  - closing_brace
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - dynamic_inline
  - empty_count
  - empty_parameters
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - nesting
  - operator_whitespace
  - private_unit_test
  - return_arrow_whitespace
  - statement_position
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - unused_enumerated
  - valid_ibinspectable
  - todo
  - colon
  - trailing_comma
  - syntactic_sugar
  - opening_brace
  - vertical_whitespace
  

# MC-3985: Comment this back in
  - identifier_name

# Please leave these commented out lines below here. We can periodically turn off the whitelist and enable
# these to check for new rules to use.

# disabled_rules: # rule identifiers to exclude from running
#   - trailing_whitespace
#   - vertical_whitespace # but we should turn this on at some point
#   - opening_brace
#   - valid_docs      # until we have more time and decide on how best to document
#   - todo
#   - void_return
#
#   # to be enabled when we have time
#   - trailing_comma
#   - implicit_getter
#   - weak_delegate
#   - syntactic_sugar
#   - unused_closure_parameter
#   - redundant_string_enum_value
#   - closure_parameter_position
#   - empty_parentheses_with_trailing_closure
#   - comma
#   - colon
#
# opt_in_rules:
#    - empty_count
#    - force_unwrapping

included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  -
excluded: # paths to ignore during linting. overridden by `included`.  
  - Carthage
  - Pods
  - .git
  - BentoTests/Mocks

line_length:
  - 160
  - 200
type_body_length:
  - 300 # warning
  - 400 # error
function_body_length:
  - 60
  - 120
identifier_name:
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
